---
title: "getting-started: Amtliche Klassenstufenzahl je Schule, Schulteil und Jahr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{getting-started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Setup
```{r setup}
library(bekiths)
library(readxl)
library(dplyr)
library(tibble)
library(stringr)
library(ggplot2)
```

# Read *.xlsx Rohdaten 
+ Browse [](https://www.schulstatistik-thueringen.de) und download Daten zu im xlsx Format
+ "Schulen und Schüler nach Schulart sowie Schulstufen (Primar-, Sekundarstufe I und II) (1A5)"

```{r j1, echo=TRUE}

# Pfad zu xlsx Rodaten von https://www.schulstatistik-thueringen.de
path <- system.file("extdata", "klassenstufen", package = "bekiths")

# Position Spalten in xlsx
cols <- c(
    Schuljahr        = 1,
    School           = 8,
    Name             = 9,
    Admin            = 10,
    Kreis            = 11,
    Board            = 12,
    Schulart_filter  = 5,
    Schulart         = 13,
    PLZ              = 14,
    Ort              = 15,
    Strasse          = 16,
    AGS              = 17,
    Schulteil_NR = 18, 
    Schulteil_PLZ    = 19,
    Schulteil_Ort    = 20,
    Schulteil_Strasse = 21,
    Klassen_3        = 26,
    Schueler_3       = 27
)

# Extract Stichtags-Datum und Download-Datum
meta_specs <- list(
  stichtag = list(                   
    col = 1,
    pattern = "Stichtag:\\s*([^,]+)",
    group=1
  ),
  erstellt_am = list(                     
    col = 1,
    pattern = "erstellt am\\s*([^/]+) ",
    group=1
  )
)

# Lese alle xlsx Dateien ein und erstelle data frame
df <- read_schools(
  path = path, 
  skip=12,
  cols = cols,
  meta_specs = meta_specs)

str(df)
```

```{r j2, echo=TRUE}
# filtern und saeubern
df_tidy <- df|>
  filter(Schulart_filter == "∑")|>
  select(-Schulart_filter) |> 
  mutate(
    PLZ = gsub("D-","",PLZ),
    Schulteil_PLZ = str_pad(Schulteil_PLZ, width = 5, side = "left", pad = "0"),
    Klassen_3 = as.integer(Klassen_3),
    Schueler_3 = as.integer(Schueler_3),
    School = as.factor(School),
    Schulart = as.factor(Schulart),
    stichtag = as.POSIXct(
      stichtag,
      format = "%d.%m.%Y",
      tz = "Europe/Berlin"),
    erstellt_am = as.POSIXct(
      erstellt_am,
      format = "%d.%m.%Y %H:%M",
      tz = "Europe/Berlin"),
    Cohort = as.integer(paste0("20",gsub("/.*","",Schuljahr))))
str(df_tidy)

```

```{r j3, echo=TRUE}
# check: jede Schule pro Jahr maximal Schulteilanzahl?
df_tidy |>
  group_by(Schuljahr, School, Schulteil_NR) |>
  count() |> 
  select(Schuljahr, School,n, Schulteil_NR) |>
  filter(n > Schulteil_NR)

summary(df_tidy$Schueler_3)
```


```{r j4, echo=TRUE}
# bekannte Drittklässlerangaben
# Hinweis: es gibt auch (schulabhängig) klassenstufenübergreifende Drittklässler,
# die hier nicht mit erfasst sind

df_sum <- df_tidy |>
  filter(!is.na(Schueler_3)) |> 
  group_by(Schuljahr, stichtag) |>
  summarize(N = sum(Schueler_3), .groups = "drop") 


ggplot(df_sum, aes(x = Schuljahr, y = N)) +
  geom_col(just = 0) +
  geom_point(size = 1) +
  geom_label(aes(label = N), vjust = -0.2) +
  scale_x_discrete(
    sec.axis = dup_axis(                       # secondary axis on top
      breaks = df_sum$Schuljahr,
      labels = df_sum$stichtag,
      name   = "Stichtag Schuljahresstatistik"
    )
  ) +
  theme(
    axis.title.x.top  = element_blank(),       # optional: hide top title
    axis.text.x.top   = element_text(margin = margin(b = 5)),
    axis.text.x.bottom = element_text(margin = margin(t = 5))
  ) + 
  theme_classic() +
  labs(x = "Schuljahr",
       y = "Anzahl",
       title = "Anzahl amtilich bekannter Drittklässler", 
       caption = paste0("Daten-Quelle: schulstatistik-thueringen.de, abgerufen am: ",
                        unique(df_tidy$erstellt_am), ",
Hinweis: es gibt auch (schulabhängig) klassenstufenübergreifende Drittklässler, die hier nicht mit aufgezählt sind"))

```
